// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCurriculum.Data;

#nullable disable

namespace WebCurriculum.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241014170458_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCurriculum.Entities.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoServidor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arquivos");
                });

            modelBuilder.Entity("WebCurriculum.Entities.Curriculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Curriculos");
                });

            modelBuilder.Entity("WebCurriculum.Entities.CurriculoArquivo", b =>
                {
                    b.Property<int>("CurriculoId")
                        .HasColumnType("int");

                    b.Property<int>("ArquivoId")
                        .HasColumnType("int");

                    b.HasKey("CurriculoId", "ArquivoId");

                    b.HasIndex("ArquivoId");

                    b.ToTable("CurriculoArquivos");
                });

            modelBuilder.Entity("WebCurriculum.Entities.CurriculoArquivo", b =>
                {
                    b.HasOne("WebCurriculum.Entities.Arquivo", "Arquivo")
                        .WithMany("CurriculoArquivos")
                        .HasForeignKey("ArquivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCurriculum.Entities.Curriculo", "Curriculo")
                        .WithMany("CurriculoArquivos")
                        .HasForeignKey("CurriculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arquivo");

                    b.Navigation("Curriculo");
                });

            modelBuilder.Entity("WebCurriculum.Entities.Arquivo", b =>
                {
                    b.Navigation("CurriculoArquivos");
                });

            modelBuilder.Entity("WebCurriculum.Entities.Curriculo", b =>
                {
                    b.Navigation("CurriculoArquivos");
                });
#pragma warning restore 612, 618
        }
    }
}
